### ISSUE TITLE
enableTrickleCharge() called with random data?

### ISSUE THREAD

**Issue by kpfleming** [sparkfun/SparkFun_RV-1805_Arduino_Library#12]
https://github.com/sparkfun/SparkFun_RV-1805_Arduino_Library/blob/3b102c1a4dad8e60197ebf37ca9023d27b269d61/src/SparkFun_RV1805.cpp#L83

I'm an experienced C++ programmer but not familiar with the specifics of the Arduino IDE, so based on reading this code it appears that `enableTrickleCharge` will be invoked with random data for its two parameters, since nothing is supplied at the call site. Since these parameters control the voltage output by the trickle charger to charge the supercap, this could result in very odd behavior.

**Comment by AndyEngland521** [comment]
Hi Kevin,
This function actually has [default arguments.](https://www.geeksforgeeks.org/default-arguments-c/) These are declared in `SparkFun_RV1805.h` on line 227

`	void enableTrickleCharge(uint8_t diode = DIODE_0_3V, uint8_t rOut = ROUT_3K); //Diode default 0.3V, rOut default 3k
`

This means that if we don't pass any arguments into this function, it will use the default of a .3V diode and a 3K resistor in the trickle charger circuit.

Hope this helps!

**Comment by kpfleming** [comment]
Thanks, I should have looked in the header file but didn't. Completely my fault :-)
