### ISSUE TITLE
Issue in setting Year

### ISSUE THREAD

**Issue by vijayprakash1** [sparkfun/SparkFun_RV-1805_Arduino_Library#6]
Hi,
I am using RV-1805-C3 or my project. I have used this library for the RTC and when I am setting date - i.e: 09/02/2019 after setting when i try to get date from the RTC using stringDate() function i got 09/02/2047 seems its adding 28 in the year.
Also, I can't set the date value 08 and 09 I am getting compiler error

Please let me know if any solution is available.

**Comment by AndyEngland521** [comment]
Somehow never got the notification for this, should be all good with v1.0.4
