### ISSUE TITLE
RV-1805 High Current Draw

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_RV-1805_Arduino_Library#9]
Hi there,

Following-up on [my post on the SparkFun forums](https://forum.sparkfun.com/viewtopic.php?p=210820#p210820), as it stands, this library will result in a current draw of ~0.64 mA (643 uA) by the RV-1805 module. This is due to the fact that the PSW and RST open drain outputs do not correctly have a 3.3V source applied to them.

As best I can tell, in order to resolve this issue, the library should be by default setting the following registers:

RSTP bit (bit 3) in the Control1 (10h) register to 1 (sets RST pin HIGH)
LKP bit (bit 5) of the Oscillator Status Register (1Dh) to 0 (unlocks PSWB)
PSWB bit (bit 5) in the Control1 (10h) register to 1 (turns off PSW switch)

After making these changes I was able to achieve a current draw of 225 nA (0.25 uA).

Cheers,
Adam

**Comment by AndyEngland521** [comment]
Thanks Adam, I've pulled these changes in and added them to v1.0.7
